### ISSUE TITLE
VAC: Adicionar opção para selecionar arquivo do Drive

### ISSUE THREAD

**Issue by arufonsekun** [optidatacloud/vue-advanced-chat#41]
### Descrição 📝 
* Customizar esse dropdown para aparecer a opção de selecionar arquivo do drive;
![image](https://github.com/optidatacloud/vue-advanced-chat/assets/19571204/14b0d4c6-66fd-43bc-8663-60273df13270)

**Comment by arufonsekun** [comment]
Assim:
![image](https://github.com/optidatacloud/vue-advanced-chat/assets/19571204/fe444e6a-5c1e-4609-b507-c863142e45f1)

**Comment by jeanchilger** [comment]
Imagino que esta tarefa será feita junto à https://github.com/optidatacloud/optiwork-web-chat/issues/182
