### ISSUE TITLE
VAC: Emitir evento quando usuário clicar na resposta de uma mensagem

### ISSUE THREAD

**Issue by arufonsekun** [optidatacloud/vue-advanced-chat#50]
### Descrição 📝 
* Emitir novo evento quando o usuário clicar na reply de uma mensagem;
* Nesse evento deve ser informado qual message reply está sendo clicada;
* Ele será usado pelo Optiwork Chat pra implementar o scroll para a mensagem respondida;
* UI: adicionar cursor pointer na reply pra que o usuário saiba que dá pra clicar;
![image](https://github.com/optidatacloud/vue-advanced-chat/assets/19571204/81337ec9-f3ad-4168-91ea-ac8846252e59)

**Comment by arufonsekun** [comment]
Fazendo essa junto com https://github.com/optidatacloud/optiwork-web-chat/issues/439

**Comment by jeanchilger** [comment]
Robei essa
